# Generated by Django 4.2.1 on 2023-06-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
