# Generated by Django 4.2.1 on 2023-05-05 07:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=20)),
                ('organization_or_college', models.CharField(default='LD college', max_length=120)),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField(default=datetime.datetime(2023, 5, 5, 7, 30, 1, 546138))),
                ('venue', models.CharField(max_length=120, null=True)),
                ('about', models.TextField(null=True)),
                ('contact_number', models.IntegerField(default='999999999')),
                ('contact_email', models.EmailField(default='info@allevents.com', max_length=254)),
                ('contact_number_2', models.IntegerField(blank=True, null=True)),
                ('contact_email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('instance_created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('fast_check', models.BooleanField(default=True)),
                ('pass_template', models.ImageField(blank=True, null=True, upload_to='media/<django.db.models.fields.related.ForeignKey>/events/')),
                ('event_coordinates', models.BooleanField(default=False)),
                ('qr_code_coordinates', models.TextField()),
                ('name_coordinates', models.TextField()),
                ('pre_define_pass', models.BooleanField(default=False)),
                ('predefined_pass_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('event_update_count', models.IntegerField(default=0)),
                ('removed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('invitees', models.ManyToManyField(blank=True, related_name='all_events', to='accounts.invitee')),
                ('moderators', models.ManyToManyField(blank=True, related_name='events_as_moderator', to=settings.AUTH_USER_MODEL)),
                ('recognized_invitees', models.ManyToManyField(blank=True, related_name='attended_all_events', to='accounts.invitee')),
            ],
            options={
                'unique_together': {('created_by', 'unique_id')},
            },
        ),
    ]
