# Generated by Django 4.2.1 on 2023-06-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitee', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitees',
            field=models.ManyToManyField(blank=True, related_name='all_events', to='invitee.invitee'),
        ),
    ]
