# Generated by Django 4.2.1 on 2023-05-05 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 7, 30, 6, 148422)),
        ),
    ]
