# Generated by Django 4.2.1 on 2023-06-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datePrice', '0002_dateprice_datetime_dateprice_price_virtualmodel_and_more'),
        ('events', '0002_event_invitees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='offline_events',
            field=models.ManyToManyField(blank=True, null=True, related_name='all_online_events', to='datePrice.offlinemodel'),
        ),
        migrations.AddField(
            model_name='event',
            name='online_events',
            field=models.ManyToManyField(blank=True, null=True, related_name='all_online_events', to='datePrice.virtualmodel'),
        ),
    ]
