# Generated by Django 4.2.1 on 2023-06-03 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0002_festmodel_about_festmodel_removed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_event_offline_events_event_online_events'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('created_by', 'event_name')},
        ),
        migrations.AddField(
            model_name='event',
            name='fest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fest.festmodel'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization_or_college',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
