# Generated by Django 4.2.1 on 2023-05-05 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 9, 16, 13, 182504)),
        ),
    ]
