# Generated by Django 4.2.1 on 2023-05-24 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('datePrice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateprice',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dateprice',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='VirtualModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('date_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datePrice.dateprice')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='OfflineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('place', models.TextField()),
                ('date_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datePrice.dateprice')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
