# Generated by Django 4.2.1 on 2023-06-04 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_created_by'),
        ('invitee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_invitees', to='events.event'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='other_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='pass_template',
            field=models.ImageField(blank=True, null=True, upload_to='media/<django.db.models.fields.related.ForeignKey>/invitees_pass/'),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
