# Generated by Django 3.2.13 on 2022-04-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220421_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='passmodel',
            name='recognized',
            field=models.BooleanField(default=False),
        ),
    ]
