# Generated by Django 3.2.13 on 2022-04-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_passmodel_recognized'),
    ]

    operations = [
        migrations.AddField(
            model_name='passmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
