# Generated by Django 3.2.13 on 2022-04-22 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_passmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passmodel',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
