# Generated by Django 4.2.1 on 2023-05-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('unique_id', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('other_info', models.TextField()),
                ('recognized', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, upload_to='media/<django.db.models.fields.related.ForeignKey>/None/invitees/')),
                ('pass_template', models.ImageField(blank=True, upload_to='media/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>/invitees_pass/')),
                ('sent_email', models.BooleanField(default=False)),
            ],
        ),
    ]
