# Generated by Django 4.2.1 on 2023-05-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='media/invitees/'),
        ),
    ]
