# Generated by Django 4.2.1 on 2023-05-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_invitee_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
